#!/bin/bash

sv d /etc/service/srk-ua-responder
sv d /etc/service/srk-ua-helper
sv d /etc/service/srk-ua-rssh

rm -rf /etc/service/srk*

rm -rf /etc/apache2/sites-enabled/sark*

[ -L /etc/fail2ban/jail.local ] && rm -rf /etc/fail2ban/jail.local
[ -L /etc/fail2ban/action.d/shorewall.local ] && rm -rf /etc/fail2ban/action.d/shorewall.local
[ -L /etc/fail2ban/filter.d/asterisk.conf ] && rm -rf /etc/fail2ban/filter.d/asterisk.conf 

[ -e /etc/sudoers.d/sarkrssh ] && rm -rf /etc/sudoers.d/sarkrssh 

# stretch teardown


systemctl disable  debsetlan
